---
- name: Deploy
  hosts: localhost
  connection: local
  gather_facts: no
  become: false

  vars_files:
    - ../../base/util/vault/vault.yml
  roles:
    #- namespace
    - service-account
    #- delete-all
    #- database
