---
- name: Deploy
  hosts: localhost
  connection: local
  gather_facts: no
  become: false

  vars_files:
    #- /home/ubuntu/.secrets/secrets.yaml
    #- vars/main.yaml
    - ../../base/util/vault/vault.yml
  roles:
    # - namespace
    - delete-all
    - database
