---
- name: Deploy
  hosts: localhost
  connection: local
  gather_facts: no
  become: false

  vars_files:
    - /home/ubuntu/.secrets/secrets.yaml
    - /km-gcp/util/setup/vars/main.yml
    - vars/main.yaml
  
  roles:
    - environment
    # - deployment
