---
apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    name: model-trainer-service
spec:
  ports:
  - port: 8501
    targetPort: 8501 # 8080 # 8501
    nodePort: 30036
    protocol: TCP
    name: http
  selector:
    app: model-trainer
  type: LoadBalancer
status:
    loadBalancer: {}