runtime: custom
env: flex
instance_class: B2
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 5
  disk_size_gb: 25
env_variables:
  GCS_BUCKET: "{{ secrets.projects.auto-finder.bucket }}"
