apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: frontend
build:
  artifacts:
  - image: streamlit
    context: ./app/
  local:
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
    - ./app/kubernetes/k8s-deploy.yml
    - ./app/kubernetes/k8s-service.yml
portForward:
  - resourceType: deployment
    resourceName: streamlit-webapp
