apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: streamlit-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: streamlit-webapp
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
            #type: AverageValue
          #averageValue: 200Mi
