---
apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    name: streamlit-webapp-service
spec:
  ports:
  - port: 8501 # 80
    targetPort: 8501 # 8080 # 8501
    protocol: TCP
    name: http
  selector:
    app: streamlit-webapp
  type: LoadBalancer
status:
    loadBalancer: {}