---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: streamlit-webapp-service
#  namespace: at-app-frontend
spec:
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: streamlit-webapp
  type: NodePort
#status:
#    loadBalancer: {}



